title: "MasIpinArifin's Blog"
email: masipinarifin@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: MasIpinArifin
paginate: 30
disqus: 'disqus_DRrRTCJ83k'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-MYGH9YKBDT
drafts: true

# Authors
authors:
  MasIpinArifin:
    name: Nurul Arifin
    display_name: MasIpinArifin
    avatar: 'assets/images/MasIpinArifin.png'
    email: masipinarifin@gmail.com
    web: https://masipinarifin.github.io
    twitter: https://twitter.com/MasIpinArifin
    description: "Penikmat Kopi Saset dan Mi Ayam."
#  john:
#    name: John
#    display_name: John
#    avatar: 'assets/images/john.png'
#    email: wowthemesnet@gmail.com
#    web: https://www.wowthemes.net/category/jekyll-themes/
#    twitter: https://twitter.com/wowthemesnet
#    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/masipinarifin/
  facebook: https://www.facebook.com/maz.ipin
  twitter: https://twitter.com/MasIpinArifin

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives